### PR TITLE
Depth parameter buggy

### PR DESCRIPTION
**Pull request by Jako**

### CODE REVIEW

**Comment by Jako** [comment]
The depth parameter seems not to work with `&parents=`0``. Works fine with `&parents=`+0``

**Comment by bezumkin** [comment]
If parents is set to 0 there is no limit for parents and their depth.

**Comment by Jako** [comment]
But why there is no depth limit with `&parents=`0``?

**Comment by bezumkin** [comment]
Because parents do not limit the query.

Depth - it is a parents parameter. If we do not have any parents, from what we must count depth?

If you want to limit depth from root of site, please specify the root by 

```
&parents=`+0`
```

If you do not want to limit the query by parents, please specify

```
&parents=`0`
```

You can simply view the difference, by enabling the &showLog parameter and see the raw SQL of this two queries.

**Comment by Jako** [comment]
O.k. If the sql query has to be shorter this is an option – but it has to be documented somewhere. Without looking in the code I would not have known that `+` is possible as prefix in `&parent`.

I would prefer something like `&resources=`all`` to retreive all resources. That option would disable any parents/depth settings then.

**Comment by bezumkin** [comment]
You can document everything you want - https://github.com/bezumkin/Docs

http://docs.modx.pro/en/components/pdotools/

**Comment by Jako** [comment]
> If we do not have any parents, from what we must count depth?

`&parents=`0`` is `&parents=`modxroot`` in most snippets (`&startId` in Wayfinder) and from modx root you could count the depth.

**Comment by bezumkin** [comment]
Well, you can continue use Wayfinder and getResources if you more like them. I don`t mind.

pdoTools is not Wayfinder or getResources, sorry.

**Comment by Jako** [comment]
I just have tried to argue, that `&parents=`0`` disabling `&depth` is a sort of trap and what seems to be more logical for me (`&documents=`all`` vs. `&parents=`0``).

I won't use Wayfinder and getResources anymore because of speed issues – pdoTools are lot better.

Have done a PR for the english documentation on http://docs.modx.pro/

**Pull request closed without merging**
